version: "3"
services:
	mysql:
		container_name: 'mysql'
		image: mysql:5.7
		restart: always
		ports: 
			- 3307:3306
		environment: 
			MYSQL_ROOT_PASSWORD: aramis29
			MYSQL_DATABASE: baltazar
			MYSQL_USER: root
			MYSQL_PASSWORD: root
		networks: 
			- microservices
		volumes:
			- "./data:/var/lib/mysql "
	phpmyadmin:
		container_name: 'microservices-phpmyadmin'
		image: phpmyadmin/phpmyadmin
		networks: 
			- microservices
		environment: 
			PMA_HOST: mysql
			PMA_PORT: 3306
		ports: 
			- '8088:80'
		volumes: 
			- /sessions
	aplicacao:
		container_name: 'application_microservice'
		image: webdevops/php-apache-dev:alpine
		ports: 
			- 81:80
		volumes: 
			- "\Users\davison.f.nascimento\Documents\Developer\:/app "
		networks: 
			- microservices
networks: 
	microservices: